name: Release to Maven Central

on:
  push:
    branches:
      - main
      - release

jobs:
  release:
    name: Deploy to Maven Central
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: "maven"

      - name: Import GPG key
        run: |
          echo "$GPG_PRIVATE_KEY" | gpg --batch --yes --import

          echo "ðŸ“¦ Listing secret keys:"
          gpg --list-secret-keys --keyid-format=long

          KEY_ID=$(gpg --list-secret-keys --with-colons | awk -F: '/^sec/ { print $5 }')

          echo "ðŸ” Setting trust level for key: $KEY_ID"

          echo -e "5\ny\n" | gpg --batch --yes --command-fd 0 --edit-key "$KEY_ID" trust
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}

      - name: Set up Maven settings
        run: |
          mkdir -p ~/.m2
          sed -e "s|{{MAVEN_CENTRAL_USERNAME}}|${{ secrets.MAVEN_CENTRAL_USERNAME }}|g" \
              -e "s|{{MAVEN_CENTRAL_PASSWORD}}|${{ secrets.MAVEN_CENTRAL_PASSWORD }}|g" \
              -e "s|{{GPG_PRIVATE_KEY}}|${{ secrets.GPG_PRIVATE_KEY }}|g" \
              -e "s|{{GPG_PASSPHRASE}}|${{ secrets.GPG_PASSPHRASE }}|g" \
          .github/resources/settings-template.xml > ~/.m2/settings.xml

      - name: Build and Deploy
        run: mvn -B clean deploy
